# Site settings
title: Tech Lead in Robotics
description: A portfolio site for a tech lead in robotics
url: "https://yourusername.github.io/vsketti"

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Social links
social_links:
  - title: GitHub
    url: https://github.com/yourusername
  - title: LinkedIn
    url: https://linkedin.com/in/vschettino

# Custom styles
custom_css:
  - "/dark-mode.css"
  - "/custom.css"

# Profile picture
profile_picture: "/me.png"

